on: push
name: Build and release on push
jobs:
  release:
    name: create release artifacts 
    runs-on: ubuntu-latest
    steps:
      - name: clone edgex examples repo
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}

      - name: Print github workspace
        run: echo $GITHUB_WORKSPACE && pwd && echo ${{ github.workspace }} 

      - name: tar zip edgex jakarta helm directory
        shell: bash
        run: |
          (cd $GITHUB_WORKSPACE/deployment && tar -czvf edgex-examples-helm.tar.gz helm)

      - name: tar zip edgex jakarta helm
        uses: fnkr/github-action-ghr@v1
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GHR_REPLACE: true
          GHR_PATH: ${{ github.workspace }}/deployment/edgex-examples-helm.tar.gz
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
