on: push
name: Build and release on push
jobs:
  release:
    name: create release artifacts 
    runs-on: ubuntu-latest
    steps:
      - name: clone edgex examples repo
        uses: actions/checkout@v3
        with:
          ref: release_action
      - name: tar zip edgex jakarta helm
        uses: fnkr/github-action-ghr@v1
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GHR_COMPRESS: gz
          GHR_PATH: edgex-examples/deployment/helm 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
